# fly.toml app configuration file generated for notefinder on 2026-09-11T11:03:47-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notefinder'
primary_region = 'gru'

[build]
    image = "ghcr.io/theryston/notefinder:latest"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512MB'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
